// Creator Record generator — implements CREATOR_POLICY §2.
// Every external research event yields a signed Markdown record attributing
// the result to its authors and the Platform to Evan Ketchum.

import type { UnlockEvent } from "./world-store";
import { getBreakthrough } from "./world-store";

export const PLATFORM_CREATOR = "Evan Ketchum";

export function buildCreatorRecord(ev: UnlockEvent): string {
  const bt = getBreakthrough(ev.id);
  const ts = new Date(ev.unlockedAt).toISOString();
  const kind = ev.source === "external_research" ? "external_research" : "simulation";
  const authors = ev.authors && ev.authors.length ? ev.authors.join(", ") : ev.discoveredBy;
  const refs = (ev.references || []).map((r) => `- ${r}`).join("\n") || "_(none provided)_";
  return [
    `# Creator Record — ${bt?.name ?? ev.id}`,
    ``,
    `- **Breakthrough ID:** ${ev.id}`,
    `- **Class:** ${kind}`,
    `- **Tier / Category:** T${bt?.tier ?? "?"} · ${bt?.category ?? "?"} · ${bt?.realityTag ?? "?"}`,
    `- **Result author(s):** ${authors}`,
    `- **Platform Creator:** ${PLATFORM_CREATOR}`,
    `- **Timestamp (ISO):** ${ts}`,
    ev.runCardId ? `- **Run Card:** ${ev.runCardId}` : null,
    ev.notes ? `- **Notes:** ${ev.notes}` : null,
    ``,
    `## Summary`,
    bt?.summary ?? "_(no catalog entry)_",
    ``,
    `## References`,
    refs,
    ``,
    `## Attribution Statement`,
    kind === "external_research"
      ? `Scientific credit for this result belongs to ${authors}. The Quantara Platform (architecture, engine, world mechanics, ledger, 3D/4D bridge) is the work of ${PLATFORM_CREATOR}. Per the Quantara Creator Policy §3, ${PLATFORM_CREATOR} does not claim scientific authorship of this result.`
      : `This entry is a Class A autonomous simulation event generated by Quantara World bots. It is curated content for worldbuilding and education and is NOT a real scientific result (Creator Policy §1, §5). Platform Creator: ${PLATFORM_CREATOR}.`,
    ``,
    `_Generated by Quantara Platform at ${new Date().toISOString()}._`,
  ]
    .filter(Boolean)
    .join("\n");
}

export function downloadCreatorRecord(ev: UnlockEvent) {
  const md = buildCreatorRecord(ev);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `creator-record-${ev.id}-${ev.unlockedAt}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
