/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as SynthesisRouteImport } from './routes/synthesis'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldLedgerRouteImport } from './routes/world.ledger'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalResearchLicenseRouteImport } from './routes/legal.research-license'
import { Route as LegalCreatorPolicyRouteImport } from './routes/legal.creator-policy'
import { Route as LegalCommercialLicenseRouteImport } from './routes/legal.commercial-license'
import { Route as LegalCollaboratorsRouteImport } from './routes/legal.collaborators'
import { Route as LegalBlueprintRouteImport } from './routes/legal.blueprint'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const SynthesisRoute = SynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldLedgerRoute = WorldLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => WorldRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalResearchLicenseRoute = LegalResearchLicenseRouteImport.update({
  id: '/research-license',
  path: '/research-license',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCreatorPolicyRoute = LegalCreatorPolicyRouteImport.update({
  id: '/creator-policy',
  path: '/creator-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCommercialLicenseRoute = LegalCommercialLicenseRouteImport.update({
  id: '/commercial-license',
  path: '/commercial-license',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCollaboratorsRoute = LegalCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => LegalRoute,
} as any)
const LegalBlueprintRoute = LegalBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => LegalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/benchmarks': typeof BenchmarksRoute
  '/ledger': typeof LedgerRoute
  '/legal': typeof LegalRouteWithChildren
  '/synthesis': typeof SynthesisRoute
  '/world': typeof WorldRouteWithChildren
  '/legal/blueprint': typeof LegalBlueprintRoute
  '/legal/collaborators': typeof LegalCollaboratorsRoute
  '/legal/commercial-license': typeof LegalCommercialLicenseRoute
  '/legal/creator-policy': typeof LegalCreatorPolicyRoute
  '/legal/research-license': typeof LegalResearchLicenseRoute
  '/legal/terms': typeof LegalTermsRoute
  '/world/ledger': typeof WorldLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/benchmarks': typeof BenchmarksRoute
  '/ledger': typeof LedgerRoute
  '/legal': typeof LegalRouteWithChildren
  '/synthesis': typeof SynthesisRoute
  '/world': typeof WorldRouteWithChildren
  '/legal/blueprint': typeof LegalBlueprintRoute
  '/legal/collaborators': typeof LegalCollaboratorsRoute
  '/legal/commercial-license': typeof LegalCommercialLicenseRoute
  '/legal/creator-policy': typeof LegalCreatorPolicyRoute
  '/legal/research-license': typeof LegalResearchLicenseRoute
  '/legal/terms': typeof LegalTermsRoute
  '/world/ledger': typeof WorldLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/benchmarks': typeof BenchmarksRoute
  '/ledger': typeof LedgerRoute
  '/legal': typeof LegalRouteWithChildren
  '/synthesis': typeof SynthesisRoute
  '/world': typeof WorldRouteWithChildren
  '/legal/blueprint': typeof LegalBlueprintRoute
  '/legal/collaborators': typeof LegalCollaboratorsRoute
  '/legal/commercial-license': typeof LegalCommercialLicenseRoute
  '/legal/creator-policy': typeof LegalCreatorPolicyRoute
  '/legal/research-license': typeof LegalResearchLicenseRoute
  '/legal/terms': typeof LegalTermsRoute
  '/world/ledger': typeof WorldLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/benchmarks'
    | '/ledger'
    | '/legal'
    | '/synthesis'
    | '/world'
    | '/legal/blueprint'
    | '/legal/collaborators'
    | '/legal/commercial-license'
    | '/legal/creator-policy'
    | '/legal/research-license'
    | '/legal/terms'
    | '/world/ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/benchmarks'
    | '/ledger'
    | '/legal'
    | '/synthesis'
    | '/world'
    | '/legal/blueprint'
    | '/legal/collaborators'
    | '/legal/commercial-license'
    | '/legal/creator-policy'
    | '/legal/research-license'
    | '/legal/terms'
    | '/world/ledger'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/benchmarks'
    | '/ledger'
    | '/legal'
    | '/synthesis'
    | '/world'
    | '/legal/blueprint'
    | '/legal/collaborators'
    | '/legal/commercial-license'
    | '/legal/creator-policy'
    | '/legal/research-license'
    | '/legal/terms'
    | '/world/ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  BenchmarksRoute: typeof BenchmarksRoute
  LedgerRoute: typeof LedgerRoute
  LegalRoute: typeof LegalRouteWithChildren
  SynthesisRoute: typeof SynthesisRoute
  WorldRoute: typeof WorldRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthesis': {
      id: '/synthesis'
      path: '/synthesis'
      fullPath: '/synthesis'
      preLoaderRoute: typeof SynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/ledger': {
      id: '/world/ledger'
      path: '/ledger'
      fullPath: '/world/ledger'
      preLoaderRoute: typeof WorldLedgerRouteImport
      parentRoute: typeof WorldRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/research-license': {
      id: '/legal/research-license'
      path: '/research-license'
      fullPath: '/legal/research-license'
      preLoaderRoute: typeof LegalResearchLicenseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/creator-policy': {
      id: '/legal/creator-policy'
      path: '/creator-policy'
      fullPath: '/legal/creator-policy'
      preLoaderRoute: typeof LegalCreatorPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/commercial-license': {
      id: '/legal/commercial-license'
      path: '/commercial-license'
      fullPath: '/legal/commercial-license'
      preLoaderRoute: typeof LegalCommercialLicenseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/collaborators': {
      id: '/legal/collaborators'
      path: '/collaborators'
      fullPath: '/legal/collaborators'
      preLoaderRoute: typeof LegalCollaboratorsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/blueprint': {
      id: '/legal/blueprint'
      path: '/blueprint'
      fullPath: '/legal/blueprint'
      preLoaderRoute: typeof LegalBlueprintRouteImport
      parentRoute: typeof LegalRoute
    }
  }
}

interface LegalRouteChildren {
  LegalBlueprintRoute: typeof LegalBlueprintRoute
  LegalCollaboratorsRoute: typeof LegalCollaboratorsRoute
  LegalCommercialLicenseRoute: typeof LegalCommercialLicenseRoute
  LegalCreatorPolicyRoute: typeof LegalCreatorPolicyRoute
  LegalResearchLicenseRoute: typeof LegalResearchLicenseRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalBlueprintRoute: LegalBlueprintRoute,
  LegalCollaboratorsRoute: LegalCollaboratorsRoute,
  LegalCommercialLicenseRoute: LegalCommercialLicenseRoute,
  LegalCreatorPolicyRoute: LegalCreatorPolicyRoute,
  LegalResearchLicenseRoute: LegalResearchLicenseRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface WorldRouteChildren {
  WorldLedgerRoute: typeof WorldLedgerRoute
}

const WorldRouteChildren: WorldRouteChildren = {
  WorldLedgerRoute: WorldLedgerRoute,
}

const WorldRouteWithChildren = WorldRoute._addFileChildren(WorldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  BenchmarksRoute: BenchmarksRoute,
  LedgerRoute: LedgerRoute,
  LegalRoute: LegalRouteWithChildren,
  SynthesisRoute: SynthesisRoute,
  WorldRoute: WorldRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
