/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldRouteImport } from './routes/world'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SynthesisRouteImport } from './routes/synthesis'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RgRunningRouteImport } from './routes/rg-running'
import { Route as QuantumDemoRouteImport } from './routes/quantum-demo'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MathLogRouteImport } from './routes/math-log'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as KveRouteImport } from './routes/kve'
import { Route as InterstellarRouteImport } from './routes/interstellar'
import { Route as InstitutionRouteImport } from './routes/institution'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CernRouteImport } from './routes/cern'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AnnexRouteImport } from './routes/annex'
import { Route as AncestralRouteImport } from './routes/ancestral'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldLedgerRouteImport } from './routes/world.ledger'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalResearchLicenseRouteImport } from './routes/legal.research-license'
import { Route as LegalLicenseRouteImport } from './routes/legal.license'
import { Route as LegalCreatorPolicyRouteImport } from './routes/legal.creator-policy'
import { Route as LegalCommercialLicenseRouteImport } from './routes/legal.commercial-license'
import { Route as LegalCollaboratorsRouteImport } from './routes/legal.collaborators'
import { Route as LegalBlueprintRouteImport } from './routes/legal.blueprint'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiQedRouteImport } from './routes/api/qed'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiBenchmarkRouteImport } from './routes/api/benchmark'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminEmailHealthRouteImport } from './routes/admin.email-health'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailHealthRouteImport } from './routes/lovable/email/health'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SynthesisRoute = SynthesisRouteImport.update({
  id: '/synthesis',
  path: '/synthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RgRunningRoute = RgRunningRouteImport.update({
  id: '/rg-running',
  path: '/rg-running',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumDemoRoute = QuantumDemoRouteImport.update({
  id: '/quantum-demo',
  path: '/quantum-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MathLogRoute = MathLogRouteImport.update({
  id: '/math-log',
  path: '/math-log',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const KveRoute = KveRouteImport.update({
  id: '/kve',
  path: '/kve',
  getParentRoute: () => rootRouteImport,
} as any)
const InterstellarRoute = InterstellarRouteImport.update({
  id: '/interstellar',
  path: '/interstellar',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRoute = InstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CernRoute = CernRouteImport.update({
  id: '/cern',
  path: '/cern',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnexRoute = AnnexRouteImport.update({
  id: '/annex',
  path: '/annex',
  getParentRoute: () => rootRouteImport,
} as any)
const AncestralRoute = AncestralRouteImport.update({
  id: '/ancestral',
  path: '/ancestral',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldLedgerRoute = WorldLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => WorldRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalResearchLicenseRoute = LegalResearchLicenseRouteImport.update({
  id: '/research-license',
  path: '/research-license',
  getParentRoute: () => LegalRoute,
} as any)
const LegalLicenseRoute = LegalLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCreatorPolicyRoute = LegalCreatorPolicyRouteImport.update({
  id: '/creator-policy',
  path: '/creator-policy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCommercialLicenseRoute = LegalCommercialLicenseRouteImport.update({
  id: '/commercial-license',
  path: '/commercial-license',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCollaboratorsRoute = LegalCollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => LegalRoute,
} as any)
const LegalBlueprintRoute = LegalBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => LegalRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQedRoute = ApiQedRouteImport.update({
  id: '/api/qed',
  path: '/api/qed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBenchmarkRoute = ApiBenchmarkRouteImport.update({
  id: '/api/benchmark',
  path: '/api/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailHealthRoute = AdminEmailHealthRouteImport.update({
  id: '/admin/email-health',
  path: '/admin/email-health',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailHealthRoute = LovableEmailHealthRouteImport.update({
  id: '/lovable/email/health',
  path: '/lovable/email/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ancestral': typeof AncestralRoute
  '/annex': typeof AnnexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/benchmarks': typeof BenchmarksRoute
  '/cern': typeof CernRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/institution': typeof InstitutionRoute
  '/interstellar': typeof InterstellarRoute
  '/kve': typeof KveRoute
  '/ledger': typeof LedgerRoute
  '/legal': typeof LegalRouteWithChildren
  '/math-log': typeof MathLogRoute
  '/pricing': typeof PricingRoute
  '/quantum-demo': typeof QuantumDemoRoute
  '/rg-running': typeof RgRunningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/world': typeof WorldRouteWithChildren
  '/admin/email-health': typeof AdminEmailHealthRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/benchmark': typeof ApiBenchmarkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/qed': typeof ApiQedRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/blueprint': typeof LegalBlueprintRoute
  '/legal/collaborators': typeof LegalCollaboratorsRoute
  '/legal/commercial-license': typeof LegalCommercialLicenseRoute
  '/legal/creator-policy': typeof LegalCreatorPolicyRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/research-license': typeof LegalResearchLicenseRoute
  '/legal/terms': typeof LegalTermsRoute
  '/world/ledger': typeof WorldLedgerRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/lovable/email/health': typeof LovableEmailHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ancestral': typeof AncestralRoute
  '/annex': typeof AnnexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/benchmarks': typeof BenchmarksRoute
  '/cern': typeof CernRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/institution': typeof InstitutionRoute
  '/interstellar': typeof InterstellarRoute
  '/kve': typeof KveRoute
  '/ledger': typeof LedgerRoute
  '/legal': typeof LegalRouteWithChildren
  '/math-log': typeof MathLogRoute
  '/pricing': typeof PricingRoute
  '/quantum-demo': typeof QuantumDemoRoute
  '/rg-running': typeof RgRunningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/world': typeof WorldRouteWithChildren
  '/admin/email-health': typeof AdminEmailHealthRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/benchmark': typeof ApiBenchmarkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/qed': typeof ApiQedRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/blueprint': typeof LegalBlueprintRoute
  '/legal/collaborators': typeof LegalCollaboratorsRoute
  '/legal/commercial-license': typeof LegalCommercialLicenseRoute
  '/legal/creator-policy': typeof LegalCreatorPolicyRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/research-license': typeof LegalResearchLicenseRoute
  '/legal/terms': typeof LegalTermsRoute
  '/world/ledger': typeof WorldLedgerRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/lovable/email/health': typeof LovableEmailHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ancestral': typeof AncestralRoute
  '/annex': typeof AnnexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/benchmarks': typeof BenchmarksRoute
  '/cern': typeof CernRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/institution': typeof InstitutionRoute
  '/interstellar': typeof InterstellarRoute
  '/kve': typeof KveRoute
  '/ledger': typeof LedgerRoute
  '/legal': typeof LegalRouteWithChildren
  '/math-log': typeof MathLogRoute
  '/pricing': typeof PricingRoute
  '/quantum-demo': typeof QuantumDemoRoute
  '/rg-running': typeof RgRunningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synthesis': typeof SynthesisRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/world': typeof WorldRouteWithChildren
  '/admin/email-health': typeof AdminEmailHealthRoute
  '/admin/logs': typeof AdminLogsRoute
  '/api/benchmark': typeof ApiBenchmarkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/qed': typeof ApiQedRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/legal/blueprint': typeof LegalBlueprintRoute
  '/legal/collaborators': typeof LegalCollaboratorsRoute
  '/legal/commercial-license': typeof LegalCommercialLicenseRoute
  '/legal/creator-policy': typeof LegalCreatorPolicyRoute
  '/legal/license': typeof LegalLicenseRoute
  '/legal/research-license': typeof LegalResearchLicenseRoute
  '/legal/terms': typeof LegalTermsRoute
  '/world/ledger': typeof WorldLedgerRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/lovable/email/health': typeof LovableEmailHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ancestral'
    | '/annex'
    | '/atlas'
    | '/auth'
    | '/benchmarks'
    | '/cern'
    | '/chat'
    | '/feedback'
    | '/institution'
    | '/interstellar'
    | '/kve'
    | '/ledger'
    | '/legal'
    | '/math-log'
    | '/pricing'
    | '/quantum-demo'
    | '/rg-running'
    | '/sitemap.xml'
    | '/synthesis'
    | '/unsubscribe'
    | '/world'
    | '/admin/email-health'
    | '/admin/logs'
    | '/api/benchmark'
    | '/api/health'
    | '/api/qed'
    | '/email/unsubscribe'
    | '/legal/blueprint'
    | '/legal/collaborators'
    | '/legal/commercial-license'
    | '/legal/creator-policy'
    | '/legal/license'
    | '/legal/research-license'
    | '/legal/terms'
    | '/world/ledger'
    | '/api/public/webhook'
    | '/lovable/email/health'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ancestral'
    | '/annex'
    | '/atlas'
    | '/auth'
    | '/benchmarks'
    | '/cern'
    | '/chat'
    | '/feedback'
    | '/institution'
    | '/interstellar'
    | '/kve'
    | '/ledger'
    | '/legal'
    | '/math-log'
    | '/pricing'
    | '/quantum-demo'
    | '/rg-running'
    | '/sitemap.xml'
    | '/synthesis'
    | '/unsubscribe'
    | '/world'
    | '/admin/email-health'
    | '/admin/logs'
    | '/api/benchmark'
    | '/api/health'
    | '/api/qed'
    | '/email/unsubscribe'
    | '/legal/blueprint'
    | '/legal/collaborators'
    | '/legal/commercial-license'
    | '/legal/creator-policy'
    | '/legal/license'
    | '/legal/research-license'
    | '/legal/terms'
    | '/world/ledger'
    | '/api/public/webhook'
    | '/lovable/email/health'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/ancestral'
    | '/annex'
    | '/atlas'
    | '/auth'
    | '/benchmarks'
    | '/cern'
    | '/chat'
    | '/feedback'
    | '/institution'
    | '/interstellar'
    | '/kve'
    | '/ledger'
    | '/legal'
    | '/math-log'
    | '/pricing'
    | '/quantum-demo'
    | '/rg-running'
    | '/sitemap.xml'
    | '/synthesis'
    | '/unsubscribe'
    | '/world'
    | '/admin/email-health'
    | '/admin/logs'
    | '/api/benchmark'
    | '/api/health'
    | '/api/qed'
    | '/email/unsubscribe'
    | '/legal/blueprint'
    | '/legal/collaborators'
    | '/legal/commercial-license'
    | '/legal/creator-policy'
    | '/legal/license'
    | '/legal/research-license'
    | '/legal/terms'
    | '/world/ledger'
    | '/api/public/webhook'
    | '/lovable/email/health'
    | '/lovable/email/suppression'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AncestralRoute: typeof AncestralRoute
  AnnexRoute: typeof AnnexRoute
  AtlasRoute: typeof AtlasRoute
  AuthRoute: typeof AuthRoute
  BenchmarksRoute: typeof BenchmarksRoute
  CernRoute: typeof CernRoute
  ChatRoute: typeof ChatRoute
  FeedbackRoute: typeof FeedbackRoute
  InstitutionRoute: typeof InstitutionRoute
  InterstellarRoute: typeof InterstellarRoute
  KveRoute: typeof KveRoute
  LedgerRoute: typeof LedgerRoute
  LegalRoute: typeof LegalRouteWithChildren
  MathLogRoute: typeof MathLogRoute
  PricingRoute: typeof PricingRoute
  QuantumDemoRoute: typeof QuantumDemoRoute
  RgRunningRoute: typeof RgRunningRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SynthesisRoute: typeof SynthesisRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WorldRoute: typeof WorldRouteWithChildren
  AdminEmailHealthRoute: typeof AdminEmailHealthRoute
  AdminLogsRoute: typeof AdminLogsRoute
  ApiBenchmarkRoute: typeof ApiBenchmarkRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQedRoute: typeof ApiQedRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
  LovableEmailHealthRoute: typeof LovableEmailHealthRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synthesis': {
      id: '/synthesis'
      path: '/synthesis'
      fullPath: '/synthesis'
      preLoaderRoute: typeof SynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rg-running': {
      id: '/rg-running'
      path: '/rg-running'
      fullPath: '/rg-running'
      preLoaderRoute: typeof RgRunningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum-demo': {
      id: '/quantum-demo'
      path: '/quantum-demo'
      fullPath: '/quantum-demo'
      preLoaderRoute: typeof QuantumDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/math-log': {
      id: '/math-log'
      path: '/math-log'
      fullPath: '/math-log'
      preLoaderRoute: typeof MathLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kve': {
      id: '/kve'
      path: '/kve'
      fullPath: '/kve'
      preLoaderRoute: typeof KveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interstellar': {
      id: '/interstellar'
      path: '/interstellar'
      fullPath: '/interstellar'
      preLoaderRoute: typeof InterstellarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution': {
      id: '/institution'
      path: '/institution'
      fullPath: '/institution'
      preLoaderRoute: typeof InstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cern': {
      id: '/cern'
      path: '/cern'
      fullPath: '/cern'
      preLoaderRoute: typeof CernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annex': {
      id: '/annex'
      path: '/annex'
      fullPath: '/annex'
      preLoaderRoute: typeof AnnexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ancestral': {
      id: '/ancestral'
      path: '/ancestral'
      fullPath: '/ancestral'
      preLoaderRoute: typeof AncestralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/ledger': {
      id: '/world/ledger'
      path: '/ledger'
      fullPath: '/world/ledger'
      preLoaderRoute: typeof WorldLedgerRouteImport
      parentRoute: typeof WorldRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/research-license': {
      id: '/legal/research-license'
      path: '/research-license'
      fullPath: '/legal/research-license'
      preLoaderRoute: typeof LegalResearchLicenseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/license': {
      id: '/legal/license'
      path: '/license'
      fullPath: '/legal/license'
      preLoaderRoute: typeof LegalLicenseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/creator-policy': {
      id: '/legal/creator-policy'
      path: '/creator-policy'
      fullPath: '/legal/creator-policy'
      preLoaderRoute: typeof LegalCreatorPolicyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/commercial-license': {
      id: '/legal/commercial-license'
      path: '/commercial-license'
      fullPath: '/legal/commercial-license'
      preLoaderRoute: typeof LegalCommercialLicenseRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/collaborators': {
      id: '/legal/collaborators'
      path: '/collaborators'
      fullPath: '/legal/collaborators'
      preLoaderRoute: typeof LegalCollaboratorsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/blueprint': {
      id: '/legal/blueprint'
      path: '/blueprint'
      fullPath: '/legal/blueprint'
      preLoaderRoute: typeof LegalBlueprintRouteImport
      parentRoute: typeof LegalRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/qed': {
      id: '/api/qed'
      path: '/api/qed'
      fullPath: '/api/qed'
      preLoaderRoute: typeof ApiQedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/benchmark': {
      id: '/api/benchmark'
      path: '/api/benchmark'
      fullPath: '/api/benchmark'
      preLoaderRoute: typeof ApiBenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-health': {
      id: '/admin/email-health'
      path: '/admin/email-health'
      fullPath: '/admin/email-health'
      preLoaderRoute: typeof AdminEmailHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/health': {
      id: '/lovable/email/health'
      path: '/lovable/email/health'
      fullPath: '/lovable/email/health'
      preLoaderRoute: typeof LovableEmailHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalBlueprintRoute: typeof LegalBlueprintRoute
  LegalCollaboratorsRoute: typeof LegalCollaboratorsRoute
  LegalCommercialLicenseRoute: typeof LegalCommercialLicenseRoute
  LegalCreatorPolicyRoute: typeof LegalCreatorPolicyRoute
  LegalLicenseRoute: typeof LegalLicenseRoute
  LegalResearchLicenseRoute: typeof LegalResearchLicenseRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalBlueprintRoute: LegalBlueprintRoute,
  LegalCollaboratorsRoute: LegalCollaboratorsRoute,
  LegalCommercialLicenseRoute: LegalCommercialLicenseRoute,
  LegalCreatorPolicyRoute: LegalCreatorPolicyRoute,
  LegalLicenseRoute: LegalLicenseRoute,
  LegalResearchLicenseRoute: LegalResearchLicenseRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface WorldRouteChildren {
  WorldLedgerRoute: typeof WorldLedgerRoute
}

const WorldRouteChildren: WorldRouteChildren = {
  WorldLedgerRoute: WorldLedgerRoute,
}

const WorldRouteWithChildren = WorldRoute._addFileChildren(WorldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AncestralRoute: AncestralRoute,
  AnnexRoute: AnnexRoute,
  AtlasRoute: AtlasRoute,
  AuthRoute: AuthRoute,
  BenchmarksRoute: BenchmarksRoute,
  CernRoute: CernRoute,
  ChatRoute: ChatRoute,
  FeedbackRoute: FeedbackRoute,
  InstitutionRoute: InstitutionRoute,
  InterstellarRoute: InterstellarRoute,
  KveRoute: KveRoute,
  LedgerRoute: LedgerRoute,
  LegalRoute: LegalRouteWithChildren,
  MathLogRoute: MathLogRoute,
  PricingRoute: PricingRoute,
  QuantumDemoRoute: QuantumDemoRoute,
  RgRunningRoute: RgRunningRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SynthesisRoute: SynthesisRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WorldRoute: WorldRouteWithChildren,
  AdminEmailHealthRoute: AdminEmailHealthRoute,
  AdminLogsRoute: AdminLogsRoute,
  ApiBenchmarkRoute: ApiBenchmarkRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiQedRoute: ApiQedRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
  LovableEmailHealthRoute: LovableEmailHealthRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
